
from setuptools import setup, find_packages

setup(
    name='tsapiness',
    version='0.0.4',
    packages=find_packages(),
    install_requires=['#', '# This file is autogenerated by pip-compile with Python 3.9', '# by the following command:', '#', '#    pip-compile requirements.in', '#', 'certifi==2024.7.4', '    # via requests', 'charset-normalizer==3.3.2', '    # via requests', 'idna==3.7', '    # via requests', 'numpy==2.0.1', '    # via pandas', 'pandas==2.2.2', '    # via pyreadstat', 'pyreadstat==1.2.7', '    # via -r requirements.in', 'python-dateutil==2.9.0.post0', '    # via pandas', 'pytz==2024.1', '    # via pandas', 'requests==2.32.3', '    # via -r requirements.in', 'six==1.16.0', '    # via python-dateutil', 'tzdata==2024.1', '    # via pandas', 'urllib3==2.2.2', '    # via requests'],
    author='Andrew Le Breuilly',
    author_email='andrew@arrowstream.co.uk',
    description='An open source python package to connect survey data to the survey definition defined by tsapi',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/ArrowstreamUK/TSAPI-py',
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.9',
)
